"""add referral system and investment credit

Revision ID: 79af783191a5
Revises: 2b2d80fc61de
Create Date: 2026-04-08 02:20:06.801588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79af783191a5'
down_revision = '2b2d80fc61de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_qualified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('first_qualified_deposit_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('investment_credit_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('referral_reward_milestones_paid', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=True)
        batch_op.create_foreign_key(
            'fk_user_referred_by_id_user',
            'user',
            ['referred_by_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referred_by_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_column('referral_reward_milestones_paid')
        batch_op.drop_column('investment_credit_balance')
        batch_op.drop_column('first_qualified_deposit_at')
        batch_op.drop_column('referral_qualified')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
